Repository ita-social-projects/EventsExpress-Frontend, pull requests merged in 2022-02, with the labels that each got.

#38 refactor: refactor some unnecessary codes(<></> and data !== undefined) (refactor remarks)
  src/components/shared/errorMessage.js
  src/components/tile/Tile.js
  src/components/tracks/track-item.js
  src/components/tracks/track.js
  src/components/tracks/tracks-filter.js
  src/components/unitOfMeasuring/unitsOfMeasuring.js
  src/components/users/UsersFilters.js
  src/containers/SearchUsers.js
  src/containers/contactAdmin/contactAdmin-filter-container.js
Labels: Code Review

#36 fix: proptypes in components folder and import in constants and conte…
  src/components/profile/profile.js
  src/components/recoverPassword/modalwind2.js
  src/components/register/register.js
  src/components/spinner/spinner.js
  src/components/unitOfMeasuring/unitOfMeasuring-item.js
  src/components/user-info/user-info.js
  src/constants/EventVisitors.js
  src/containers/DeniedUsersAction/DeniedUsersActionContainer.js
  src/containers/contactAdmin/contactAdmin-filter-container.js
Labels: fix eslint

#35 fix: fix eslint errors in event, helpers folders and in some files in components folder
  package.json
  src/components/event/MapModal/Map-modal.js
  src/components/event/SimpleModal/Simple-modal.js
  src/components/event/UserView/UserView.js
  src/components/event/filter/parts/location/location-filter.js
  src/components/event/filter/parts/organizer/organizer-filter.js
  src/components/event/filter/parts/organizer/use-delay.js
  src/components/event/map/display-location.js
  src/components/helpers/eventsForProfileUtils.js
  src/components/helpers/filterHelper.js
  src/components/helpers/form-helpers/location/location-map-with-marker.jsx
  src/components/helpers/userViewUtils.js
  src/components/home/home.js
  src/components/inventory/inventory-form-validator.js
  src/components/landing/CarouselEventCard.js
Labels: Code Review, fix eslint

#37 refactor: refactor render period function
  src/components/eventSchedule/render-period.js
Labels: Code Review

#33 Fix lint in profiles components
  src/components/left-sidebar/left-sidebar.js
  src/components/location/location.js
  src/components/profile/editProfile/ChangePassword.jsx
  src/components/profile/editProfile/editBirthday.js
  src/components/profile/editProfile/editGender.js
  src/components/profile/editProfile/editUsername.js
  src/components/profile/editProfile/linked-auths.jsx
  src/components/profile/events.js
  src/constants/profileEvents.js
Labels: fix eslint

#32 Fix lint conteiners reducers and services
  package.json
  src/containers/unitsOfMeasuring/unitOfMeasuring-item.js
  src/containers/user-role.js
  src/reducers/events-filter/index.js
  src/reducers/hub.js
  src/reducers/root.js
  src/registerServiceWorker.js
  src/services/EventsExpressService.js
  src/services/InventoryService.js
Labels: fix eslint

#44 fix: fixed propTypes warnings on landing page
  package.json
  src/components/event/EventsForProfile/EventsForProfile.js
  src/components/event/MapModal/Map-modal.js
  src/components/event/filter/expansion-panel/filter-expansion-panel.js
  src/components/event/filter/parts/location/location-filter.js
  src/components/event/filter/parts/organizer/organizer-autocomplete.js
  src/components/event/filter/parts/organizer/organizer-filter.js
  src/components/event/map/display-location.js
  src/components/event/map/display-map.js
  src/components/event/map/display-online.js
  src/components/event/share/ShareButtons.js
  src/components/eventSchedule/eventSchedule-item-view.js
  src/components/eventSchedule/eventSchedule-item.js
  src/components/eventSchedule/eventSchedule-list.js
  src/components/google-login/google-login.jsx
  src/components/helpers/Alert.js
  src/components/helpers/form-helpers/location/location-map.jsx
  src/components/helpers/form-helpers/render-date-picker.jsx
  src/components/landing/landing.js
  src/components/modal-wind/modal-wind.js
  src/components/profile/events.js
  src/containers/alert.js
  src/security/authComponent.js
Labels: Code Review

#46 fix(left-sidebar.js | filter-form.js): fixed error with undefined on landing page
  src/components/event/filter/form/filter-form.js
  src/components/event/filter/form/green-button.js
  src/containers/left-sidebar.js
Labels: bug, Code Review

#47 fix: fixed the profile functional | fixed the Find event button
  package-lock.json
  package.json
  src/components/event/EventList/Event-list.js
  src/components/event/ImageResizer/Image-resizer.js
  src/components/shared/errorMessage.js
  src/containers/register-complete-wrapper.js
Labels: bug, Code Review

#49 fix: fixed the calendar, cnahging avatar and manage notifications
  package-lock.json
  package.json
  src/components/avatar/custom-avatar.js
  src/components/helpers/DropZoneField.js
  src/components/helpers/form-helpers/render-date-pickerV2.jsx
  src/components/profile/editProfile/editBirthday.js
  src/components/profile/editProfile/editUsername.js
  src/containers/editProfileContainers/change-avatar.js
  src/containers/notificationTypes/SelectNotificationTypes.js
  src/reducers/editReducers/change_avatar.js
  src/reducers/root.js
  src/store/initialState.js
Labels: bug, Code Review

#52 fix: deleted all dispatch where used history.push
  src/actions/event/event-add-action.js
  src/actions/event/event-copy-with-edit-action.js
  src/actions/event/event-copy-without-edit-action.js
  src/actions/eventSchedule/eventSchedule-cancel-all-action.js
  src/actions/eventSchedule/eventSchedule-cancel-next-action.js
  src/actions/register/register-bind-account-action.js
  src/actions/register/register-complete-action.js
Labels: bug, Code Review

#55 fix(profile.js | ImagePreview.js): fixed errors by validateDOM and in…
  src/components/helpers/ImagePreview.js
  src/components/profile/profile.js
Labels: bug, Code Review

#60 refactor(eventform): refactor event form component
  src/components/event/EventForm/Event-form.js
Labels: Code Review, refactor component

#54 fix: fixed user profile and propTypes
  package-lock.json
  src/components/SelectNotificationTypes/CheckboxGroup.js
  src/components/avatar/custom-avatar.js
  src/components/chat/chat.js
  src/components/chat/user_chats.js
  src/components/event/EventList/Event-list.js
  src/components/event/EventsForProfile/EventsForProfile.js
  src/components/event/ParticipantGroup/Participant-group.js
  src/components/event/filter/expansion-panel/filter-expansion-panel-parts.js
  src/components/event/filter/expansion-panel/filter-expansion-panel.js
  src/components/event/filter/form/filter-form.js
  src/components/event/filter/parts/organizer/organizer-autocomplete.js
  src/components/helpers/DropZoneField.js
  src/components/helpers/Placeholder.js
  src/components/helpers/eventsForProfileUtils.js
  src/components/helpers/form-helpers/location/location-map-with-circle.jsx
  src/components/helpers/form-helpers/render-date-pickerV2.jsx
  src/components/helpers/form-helpers/render-multiselect-field.jsx
  src/components/helpers/form-helpers/render-select-field.jsx
  src/components/profile/editProfile/ChangePassword.jsx
  src/components/profile/editProfile/editUsername.js
  src/components/profile/events.js
  src/components/profile/profile.js
  src/components/profile/user-profile.js
  src/constants/indexToTabName.js
  src/containers/SearchUsers.js
  src/containers/editProfileContainers/change-avatar.js
  src/containers/editProfileContainers/editBirthdayContainer.js
  src/containers/editProfileContainers/editGenderContainer.js
  src/containers/editProfileContainers/editUsernameContainer.js
  src/containers/events-for-admin.js
  src/containers/linked-auths-wrapper.js
  src/containers/local-spinner.js
  src/containers/notificationTypes/SelectNotificationTypes.js
  src/containers/spinner.js
  src/containers/user-item-view.js
  src/security/authComponent.js
  src/services/PhotoService.js
Labels: bug, Code Review

#56 refactored component event/RenderList
  src/components/event/RenderList/RenderList.js
  src/constants/RenderListConstants.js
Labels: Code Review

#62 fix: fix issues from comments of refactoring mapModal
  src/components/event/MapModal/Map-modal.js
Labels: Code Review, refactor component

#63 fix: fixed prop types, logout, fixed alerts in login page
  src/components/Header/header.js
  src/components/login/login.js
  src/components/recoverPassword/recoverPassword.js
  src/containers/FacebookLogin.js
  src/containers/GoogleLogin.js
  src/services/EventsExpressService.js
Labels: bug, Code Review

#64 Refactor component Event-item.js
  src/components/event/EventItem/Event-item.js
  src/constants/EventItemConstants.js
Labels: Code Review

#65 refactor(Event-item-header.js): refactored the component
  src/components/event/EventItemHeader/Event-item-header.js
  src/components/event/EventItemHeader/PrintMenuItems.js
  src/components/event/EventItemHeader/PrintMenuMembers.js
  src/components/helpers/EventItemHeaderUtils.js
Labels: Code Review, refactor component

#66 fix(login.js | recoverPassword.js): fixed errors with oneOfTypes
  src/components/login/login.js
  src/components/recoverPassword/recoverPassword.js
Labels: Code Review, fix eslint

#51 Fixed bug with onclick create event
  src/components/landing/HeadArticle.js
  src/constants/HeadArticleConstants.js
Labels: Code Review

#72 feat(package.json): commitizen added to the project | EEF-60
  package.json
Labels: enhancement, Code Review

#79 feat: created slider, icon for join to event and refactored some codes | EEF-58
  package.json
  src/actions/event/event-list-action.js
  src/assets/icons/ImgJoinToEvent.svg
  src/components/MainLayout/main-layout.css
  src/components/event/EventMatrix/EventCardV2.scss
  src/components/event/EventMatrix/EventMatrix.js
  src/components/event/EventMatrix/EventMatrix.scss
  src/components/landing/CarouselEventCard.js
  src/components/landing/EventCard/EventCard.js
  src/components/landing/EventCard/EventCard.scss
  src/components/landing/EventCard/IconsEventCard/IconsEventCard.js
  src/components/landing/EventCard/IconsEventCard/IconsEventCard.scss
  src/components/landing/EventMatrix/EventMatrix.js
  src/components/landing/EventMatrix/EventMatrix.scss
  src/components/landing/EventsListItem/EventsListItem.js
  src/components/landing/EventsListItem/EventsListItem.scss
  src/components/landing/SliderForEvents/SliderForEvents.js
  src/components/landing/SliderForEvents/SliderForEvents.scss
  src/components/landing/SliderForEvents/settingsForSlider.js
  src/components/landing/landing.css
  src/components/landing/landing.js
  src/constants/landingConstants.js
  src/mockup-db/events.json
  src/services/PhotoService.js
  src/styles/_generalSettings.scss
Labels: enhancement, Code Review
